# Generated by Django 5.1.7 on 2025-03-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.AddField(
            model_name='writing',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
