# Generated by Django 5.1.7 on 2025-03-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_writing_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='date_published',
            field=models.DateField(null=True),
        ),
    ]
