# Generated by Django 5.1.7 on 2025-03-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_writing_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='author',
            new_name='coauthor',
        ),
    ]
