# Generated by Django 5.1.7 on 2025-03-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_rename_author_writing_coauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='file',
            field=models.FileField(blank=True, upload_to='writing'),
        ),
    ]
