# Generated by Django 5.1.7 on 2025-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_writing_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='link_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
