# Generated by Django 5.1.7 on 2025-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_about_link_text_about_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume_update',
            field=models.DateField(null=True),
        ),
    ]
