# Generated by Django 5.1.7 on 2025-04-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_about_resume_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
