# Generated by Django 5.1.7 on 2025-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_about_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
