# Generated by Django 5.2 on 2025-05-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='notes',
            field=models.TextField(blank=True, help_text='Not displayed.'),
        ),
    ]
